Reply
dittos/diffmonster pull request #67
Opened 2021-05-15 09:17 UTC by dittos

2021-05-15 09:17 UTC, dittos commented on src/ui/CommentThread.module.css
> +
asdf

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=src%2Fui%2FCommentThread.module.css)_</sub>

2021-05-15 10:03 UTC, dittos commented on package.json
> +    "apollo": "^2.33.2",
asdf

2021-05-15 10:03 UTC, dittos reviewed
dafsdsaf

2021-05-15 10:03 UTC, dittos commented on package.json
> +    "@apollo/client": "^3.3.18",
afsddsaf

2021-05-15 10:07 UTC, dittos reviewed
haha

2021-05-15 11:59 UTC, dittos reviewed
???

2021-05-15 12:03 UTC, dittos reviewed
???

2021-05-15 12:16 UTC, dittos commented on package.json
>    "version": "0.1.0",
ffff

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 12:30 UTC, dittos commented on package.json
>    "version": "0.1.0",
ggg

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 12:31 UTC, dittos commented on package.json
> +    "@apollo/client": "^3.3.18",
added

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 12:31 UTC, dittos commented on package.json
> -    "typescript": "3.3.1"
rem

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 12:34 UTC, dittos commented on package.json
>    "version": "0.1.0",
hhhh

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 12:58 UTC, dittos commented on package.json
>    "version": "0.1.0",
zzz

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 13:05 UTC, dittos commented on package.json
>      "@types/diff2html": "^0.0.4",
asdgsagds

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 13:22 UTC, dittos commented on package.json
>    "version": "0.1.0",
ggg

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 13:54 UTC, dittos commented on package.json
>    "version": "0.1.0",
aaa

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 13:56 UTC, dittos commented on package.json
>    "version": "0.1.0",
aaa

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 13:59 UTC, dittos commented on package.json
>    "version": "0.1.0",
aaa

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 14:27 UTC, dittos commented on package.json
>    "version": "0.1.0",
bbb

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 14:38 UTC, dittos commented on package.json
>    "private": true,
fff

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 14:38 UTC, dittos commented on package.json
>    "private": true,
ggg

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 14:38 UTC, dittos commented on package.json
>    "version": "0.1.0",
hhh

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-15 14:39 UTC, dittos commented on package.json
>    "version": "0.1.0",
zzz

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-16 11:45 UTC, dittos commented on package.json
>    "version": "0.1.0",
asdf

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-16 11:45 UTC, dittos commented on package.json
>    "version": "0.1.0",
qwer

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-16 11:56 UTC, dittos commented on package.json
>    "version": "0.1.0",
ggg

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-16 12:10 UTC, dittos-test approved these changes

2021-05-19 11:19 UTC, dittos commented on src/stores/CommentStore.ts
> -import { Subject, of } from 'rxjs';
asdf

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=src%2Fstores%2FCommentStore.ts)_</sub>

2021-05-23 12:32 UTC, dittos-test commented on src/lib/Database.ts
> +export function observeReviewStates(pullRequestId: string): Observable<{[fileId: string]: boolean}> {
cmt

2021-05-23 12:50 UTC, dittos-test requested changes

2021-05-23 12:50 UTC, dittos-test commented on package.json
>      "fuzzaldrin-plus": "^0.6.0",
asfd

2021-05-23 12:50 UTC, dittos-test reviewed
ggg

2021-05-23 13:12 UTC, dittos-test submitted a review, later dismissed

2021-05-23 13:14 UTC, dittos-test commented on src/lib/Database.ts
> +export function observeReviewStates(pullRequestId: string): Observable<{[fileId: string]: boolean}> {
asfdf

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=src%2Flib%2FDatabase.ts)_</sub>

2021-05-23 13:34 UTC, dittos-test commented on src/lib/Database.ts
> +export function observeReviewStates(pullRequestId: string): Observable<{[fileId: string]: boolean}> {
hi

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=src%2Flib%2FDatabase.ts)_</sub>

2021-05-23 13:48 UTC, dittos-test commented on package.json
>      "fuzzaldrin-plus": "^0.6.0",
aaaa

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-23 13:48 UTC, dittos-test commented on package.json
>      "fuzzaldrin-plus": "^0.6.0",
bbbb

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-23 13:48 UTC, dittos-test commented on package.json
>      "fuzzaldrin-plus": "^0.6.0",
zzzz

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-23 13:48 UTC, dittos-test commented on package.json
> -    "marked": "^0.3.18",
hhhh

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-23 14:00 UTC, dittos-test submitted a review, later dismissed

2021-05-23 14:43 UTC, dittos commented on package.json
>      "fuzzaldrin-plus": "^0.6.0",
gg

<sub>_commented via [Diff Monster](https://diff.sapzil.org/#/dittos/diffmonster/pull/67?path=package.json)_</sub>

2021-05-23 14:58 UTC, merged